# Generated by Django 2.0.1 on 2018-01-13 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='free',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facility', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('support', models.CharField(max_length=100)),
                ('telephone', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('opponent', models.CharField(max_length=100)),
                ('time', models.CharField(max_length=100)),
                ('day', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='kinder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kname', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('pnumber', models.CharField(max_length=100)),
                ('tnumber', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('tel', models.CharField(max_length=100)),
                ('classnum', models.CharField(max_length=100)),
                ('cctvnum', models.CharField(max_length=100)),
                ('commute', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='recycle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('center', models.CharField(max_length=100)),
                ('road', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('area', models.CharField(max_length=100)),
                ('vehicle', models.CharField(max_length=100)),
                ('item', models.CharField(max_length=100)),
                ('operating', models.CharField(max_length=100)),
                ('telephone', models.CharField(max_length=100)),
            ],
        ),
    ]
