# Generated by Django 2.0.1 on 2018-01-13 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kinder',
            old_name='cctvnum',
            new_name='divide',
        ),
        migrations.RenameField(
            model_name='kinder',
            old_name='city',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='kinder',
            old_name='classnum',
            new_name='snumber',
        ),
        migrations.RenameField(
            model_name='kinder',
            old_name='commute',
            new_name='types',
        ),
        migrations.RemoveField(
            model_name='kinder',
            name='kname',
        ),
        migrations.RemoveField(
            model_name='kinder',
            name='pnumber',
        ),
        migrations.RemoveField(
            model_name='kinder',
            name='tel',
        ),
        migrations.RemoveField(
            model_name='kinder',
            name='tnumber',
        ),
    ]
